# Generated by Django 2.2.27 on 2022-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20220314_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[(None, 'Rate it'), (1, '1 - Trash'), (2, '2 - Horrible'), (3, '3 - Terrible'), (4, '4 - Bad'), (5, '5 - OK'), (6, '6 - Watchable'), (7, '7 - Good'), (8, '8 - Pretty Good'), (9, '9 - Perfect'), (10, '10 - Masterpiece')], default=None, max_length=1),
        ),
    ]
