# Generated by Django 2.2.27 on 2022-03-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20220316_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
