# Generated by Django 2.2.27 on 2022-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20220316_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movie_title',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Rate it'), (1, '1 - Trash'), (2, '2 - Horrible'), (3, '3 - Terrible'), (4, '4 - Bad'), (5, '5 - OK'), (6, '6 - Watchable'), (7, '7 - Good'), (8, '8 - Pretty Good'), (9, '9 - Perfect'), (10, '10 - Masterpiece')], default=None),
        ),
    ]
